### PR TITLE
Suitability changes importer

### PR DESCRIPTION
**Pull request by lucidstack**

### CODE REVIEW

**Comment by lucidstack** [comment]
I'll just add a couple of indexes to the DB, and then this can be reviewed

**Comment by lucidstack** [comment]
Ready to go :+1:

**Comment by Levia** [comment]
It this ready to be reviewed even after the last merge?

**Comment by lucidstack** [comment]
It is now, @Levia :)

In the end I couldn't reuse the `csv_reader` method from the Base super-class, as the symbol converter creates problems in the headers. I just overrode the method and removed the conversion.

**Pull request merged**
